package com.myeshopping.returnrefundservice.entity;
public enum ReturnStatus { RETURN_REQUESTED, RETURN_APPROVED, RETURN_PICKUP_PENDING, RETURNED, RETURN_REJECTED, RETURN_CANCELLED, CANCELLED, REFUND_REQUESTED, REFUND_PROCESSING, REFUNDED, REFUND_CANCELLED, REFUND_FAILED }
