spring.application.name=notification-service
server.port=8094
spring.datasource.url=jdbc:mysql://localhost:3306/notification_db
spring.datasource.username=myeshopping
spring.datasource.password=myeshopping
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.properties.max.block.ms=5000
