spring.application.name=customer-service
server.port=8091

spring.datasource.url=jdbc:postgresql://localhost:5432/customer_db
spring.datasource.username=myeshopping
spring.datasource.password=myeshopping
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}
