package com.myeshopping.returnrefundservice.service;
import com.myeshopping.returnrefundservice.dto.ReturnRequest; import com.myeshopping.returnrefundservice.entity.*; import com.myeshopping.returnrefundservice.repository.ReturnRequestRepository; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class ReturnRefundService { private final ReturnRequestRepository repository; private static final Map<ReturnStatus,Set<ReturnStatus>> RETURN_TRANSITIONS=Map.of(ReturnStatus.RETURN_REQUESTED,Set.of(ReturnStatus.RETURN_APPROVED,ReturnStatus.RETURN_REJECTED),ReturnStatus.RETURN_APPROVED,Set.of(ReturnStatus.RETURN_PICKUP_PENDING),ReturnStatus.RETURN_PICKUP_PENDING,Set.of(ReturnStatus.RETURNED),ReturnStatus.RETURN_REJECTED,Set.of(ReturnStatus.RETURN_CANCELLED)); private static final Map<ReturnStatus,Set<ReturnStatus>> REFUND_TRANSITIONS=Map.of(ReturnStatus.RETURNED,Set.of(ReturnStatus.REFUND_REQUESTED),ReturnStatus.REFUND_REQUESTED,Set.of(ReturnStatus.REFUND_PROCESSING,ReturnStatus.REFUND_CANCELLED,ReturnStatus.REFUND_FAILED),ReturnStatus.REFUND_PROCESSING,Set.of(ReturnStatus.REFUNDED,ReturnStatus.REFUND_FAILED));
 @Transactional public ReturnRequestEntity create(ReturnRequest request){if(repository.findByOrderId(request.getOrderId()).isPresent())throw new IllegalArgumentException("Return already exists for order: "+request.getOrderId());return repository.save(ReturnRequestEntity.builder().orderId(request.getOrderId()).customerId(request.getCustomerId()).reason(request.getReason()).amount(request.getAmount()).status(ReturnStatus.RETURN_REQUESTED).build());}
 @Transactional(readOnly=true) public ReturnRequestEntity get(Long id){return repository.findById(id).orElseThrow(()->new IllegalArgumentException("Return request not found: "+id));}
 @Transactional public ReturnRequestEntity transition(Long id,String statusText){ReturnRequestEntity request=get(id);ReturnStatus target=parse(statusText);if(!RETURN_TRANSITIONS.getOrDefault(request.getStatus(),Set.of()).contains(target))throw new IllegalArgumentException("Invalid return transition from "+request.getStatus()+" to "+target);request.setStatus(target);if(target==ReturnStatus.RETURNED)request.setCompletedAt(LocalDateTime.now());return repository.save(request);}
 @Transactional public ReturnRequestEntity refund(Long id,String statusText){ReturnRequestEntity request=get(id);ReturnStatus target=parse(statusText);if(!REFUND_TRANSITIONS.getOrDefault(request.getStatus(),Set.of()).contains(target))throw new IllegalArgumentException("Invalid refund transition from "+request.getStatus()+" to "+target);request.setStatus(target);if(target==ReturnStatus.REFUNDED)request.setCompletedAt(LocalDateTime.now());return repository.save(request);}
 private ReturnStatus parse(String text){try{return ReturnStatus.valueOf(text);}catch(IllegalArgumentException e){throw new IllegalArgumentException("Unknown return/refund status: "+text);}}
}
