spring.datasource.url=${PAYMENT_DB_URL:jdbc:postgresql://localhost:5432/paymentdb}
spring.datasource.username=${POSTGRES_USER:myeshopping}
spring.datasource.password=${POSTGRES_PASSWORD:myeshopping}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
