spring.datasource.url=${ORDER_DB_URL:jdbc:postgresql://localhost:5432/order_db}
spring.datasource.username=${POSTGRES_USER:myeshopping}
spring.datasource.password=${POSTGRES_PASSWORD:myeshopping}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=order-fulfillment
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.properties.max.block.ms=5000
