spring.application.name=picking-service
server.port=8086
spring.datasource.url=jdbc:postgresql://localhost:5432/picking_db
spring.datasource.username=myeshopping
spring.datasource.password=myeshopping
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}
