spring.application.name=invoice-service
server.port=8089
spring.datasource.url=${INVOICE_DB_URL:jdbc:postgresql://localhost:5432/invoice_db}
spring.datasource.username=${POSTGRES_USER:myeshopping}
spring.datasource.password=${POSTGRES_PASSWORD:myeshopping}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
