package com.myeshopping.deliveryservice.service;
import com.myeshopping.deliveryservice.dto.DeliveryRequest; import com.myeshopping.deliveryservice.entity.*; import com.myeshopping.deliveryservice.repository.DeliveryRepository; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class DeliveryService {
 private final DeliveryRepository repository; private static final Map<DeliveryStatus,Set<DeliveryStatus>> TRANSITIONS=Map.of(DeliveryStatus.CREATED,Set.of(DeliveryStatus.IN_TRANSIT,DeliveryStatus.FAILED),DeliveryStatus.IN_TRANSIT,Set.of(DeliveryStatus.OUT_FOR_DELIVERY,DeliveryStatus.FAILED),DeliveryStatus.OUT_FOR_DELIVERY,Set.of(DeliveryStatus.DELIVERED));
 @Transactional public Delivery create(DeliveryRequest request){if(repository.findByShipmentId(request.getShipmentId()).isPresent())throw new IllegalArgumentException("Delivery already exists for shipment: "+request.getShipmentId());return repository.save(Delivery.builder().shipmentId(request.getShipmentId()).recipientName(request.getRecipientName()).status(DeliveryStatus.CREATED).build());}
 @Transactional(readOnly=true) public Delivery get(Long id){return repository.findById(id).orElseThrow(()->new IllegalArgumentException("Delivery not found: "+id));}
 @Transactional(readOnly=true) public Delivery getByShipment(Long shipmentId){return repository.findByShipmentId(shipmentId).orElseThrow(()->new IllegalArgumentException("Delivery not found for shipment: "+shipmentId));}
 @Transactional public Delivery transition(Long id,String statusText){Delivery delivery=get(id);DeliveryStatus target;try{target=DeliveryStatus.valueOf(statusText);}catch(IllegalArgumentException e){throw new IllegalArgumentException("Unknown delivery status: "+statusText);}if(!TRANSITIONS.getOrDefault(delivery.getStatus(),Set.of()).contains(target))throw new IllegalArgumentException("Invalid delivery transition from "+delivery.getStatus()+" to "+target);delivery.setStatus(target);if(target==DeliveryStatus.DELIVERED)delivery.setDeliveredAt(LocalDateTime.now());return repository.save(delivery);}
}
